# Generated by Django 4.2.7 on 2026-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=50)),
                ("avatar", models.ImageField(upload_to="team/")),
                ("desc", models.TextField()),
                ("sort", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "团队成员",
                "verbose_name_plural": "团队成员",
                "ordering": ["sort"],
            },
        ),
    ]
