# Generated by Django 4.2.7 on 2026-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='新闻封面图')),
                ('content', models.TextField(verbose_name='新闻正文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
            ],
            options={
                'verbose_name': '新闻动态',
                'verbose_name_plural': '新闻动态',
                'ordering': ['-is_top', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
