# Generated by Django 4.2.7 on 2026-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='00000000000', max_length=20, verbose_name='联系电话'),
        ),
    ]
