# Generated by Django 4.2.7 on 2026-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("client", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="case/")),
                ("desc", models.TextField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "案例",
                "verbose_name_plural": "案例",
                "ordering": ["-created_at"],
            },
        ),
    ]
