# Generated by Django 4.2.7 on 2026-02-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序（升序）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '案例分类',
                'verbose_name_plural': '案例分类',
                'ordering': ['sort'],
            },
        ),
        migrations.RemoveField(
            model_name='case',
            name='image',
        ),
        migrations.AddField(
            model_name='case',
            name='cover',
            field=models.ImageField(blank=True, upload_to='case/covers/', verbose_name='案例封面'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.CharField(blank=True, max_length=100, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='case',
            name='content',
            field=models.TextField(verbose_name='案例详情'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='desc',
            field=models.TextField(verbose_name='案例简介'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=100, verbose_name='案例标题'),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.casecategory', verbose_name='案例分类'),
        ),
    ]
