# Generated by Django 4.2.7 on 2026-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='图标类名(Font Awesome)')),
                ('title', models.CharField(max_length=50, verbose_name='优势标题')),
                ('desc', models.TextField(verbose_name='优势描述')),
                ('sort', models.IntegerField(default=0, verbose_name='排序序号')),
            ],
            options={
                'verbose_name': '核心优势',
                'verbose_name_plural': '核心优势',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='轮播标题')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='轮播图片')),
                ('link', models.URLField(blank=True, null=True, verbose_name='跳转链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='合作方名称')),
                ('logo', models.ImageField(upload_to='partner/', verbose_name='合作方logo')),
                ('link', models.URLField(blank=True, null=True, verbose_name='官网链接')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
            },
        ),
    ]
