# Generated by Django 4.2.7 on 2026-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "公司简介", "verbose_name_plural": "公司简介",},
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("sort", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "发展历程",
                "verbose_name_plural": "发展历程",
                "ordering": ["sort"],
            },
        ),
    ]
