# Generated by Django 4.2.7 on 2026-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=50)),
                ("num", models.IntegerField(default=1)),
                ("experience", models.CharField(max_length=50)),
                ("education", models.CharField(max_length=50)),
                ("salary", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "招聘岗位",
                "verbose_name_plural": "招聘岗位",
                "ordering": ["-created_at"],
            },
        ),
    ]
